#!/bin/bash

FREE_ENERGY=`pwd`
MDP=$FREE_ENERGY/MDP
GMX=/apps/gromacs/2023-gpuvolta/bin

for (( i=0; i<21; i++ ))
do
if ! grep "Finished mdrun on rank 0" Lambda_"$i"/Production_MD/md"$i".log
then
	echo Lambda $i not finished - running
	LAMBDA=$i
#	exit 0
cat <<END > job"$i".job
#!/bin/bash
#PBS -P em52
#PBS -l ncpus=12
#PBS -l ngpus=1
#PBS -q gpuvolta
#PBS -l mem=48GB
#PBS -l walltime=12:00:00
#PBS -l wd
#PBS -o NACL"$i".olog
#PBS -N NACL"$i"
#PBS -l storage=scratch/g15

module load gromacs/2022-gpuvolta

export OMP_NUM_THREADS=12

# Set some environment variables 
FREE_ENERGY=`pwd`
echo "Free energy home directory set to $FREE_ENERGY"
MDP=$FREE_ENERGY/MDP
echo ".mdp files are stored in $MDP"

# Change to the location of your GROMACS-2018 installation
#GMX=/usr/local/gromacs/bin
GMX=/apps/gromacs/2023-gpuvolta/bin

#for (( i=0; i<21; i++ ))
#do
    LAMBDA=$i

    # A new directory will be created for each value of lambda and
    # at each step in the workflow for maximum organization.

    mkdir Lambda_$LAMBDA
    cd Lambda_$LAMBDA

    ##############################
    # ENERGY MINIMIZATION STEEP  #
    ##############################
    echo "Starting minimization for lambda = $LAMBDA..." 

    mkdir EM
    cd EM

    # Iterative calls to grompp and mdrun to run the simulations
    if ! grep 'Finished mdrun' min$LAMBDA.log
	then
    $GMX/gmx grompp -f $MDP/EM/em_steep_$LAMBDA.mdp -c $FREE_ENERGY/NACL_water_fixed.gro -p $FREE_ENERGY/topol.top -o min$LAMBDA.tpr -maxwarn 2
    $GMX/gmx mdrun -deffnm min$LAMBDA -ntmpi 1 -ntomp 12
    sleep 1
else
	echo "Minimisation EM$LAMBDA complete."
fi

    #####################
    # NVT EQUILIBRATION #
    #####################
    echo "Starting constant volume equilibration..."

    cd ../
    mkdir NVT
    cd NVT
    if ! grep 'Finished mdrun' nvt$LAMBDA.log
        then
    $GMX/gmx grompp -f $MDP/NVT/nvt_$LAMBDA.mdp -c ../EM/min$LAMBDA.gro -p $FREE_ENERGY/topol.top -o nvt$LAMBDA.tpr -maxwarn 2
    $GMX/gmx mdrun -v -ntmpi 1 -ntomp 12 -deffnm nvt$LAMBDA
#    $GMX/gmx mdrun -s nvt$LAMBDA.tpr -nt 1 -v -c nvt$LAMBDA.gro
    echo "Constant volume equilibration complete."
    sleep 1
else
	echo "Constant volume equilibration NVT$LAMBDA complete."
fi


    #####################
    # NPT EQUILIBRATION #
    #####################
    echo "Starting constant pressure equilibration..."

    cd ../
    mkdir NPT
    cd NPT
    if ! grep 'Finished mdrun' npt$LAMBDA.log
then
    $GMX/gmx grompp -f $MDP/NPT/npt_$LAMBDA.mdp -c ../NVT/nvt$LAMBDA.gro -p $FREE_ENERGY/topol.top -t ../NVT/nvt$LAMBDA.cpt -o npt$LAMBDA.tpr -maxwarn 2
    $GMX/gmx mdrun -v -ntmpi 1 -ntomp 12 -deffnm npt$LAMBDA
#    $GMX/gmx mdrun -s npt$LAMBDA.tpr -nt 1 -v -c npt$LAMBDA.gro
    echo "Constant pressure equilibration complete."
    sleep 1
else
	echo "Constant pressure equilibration NPT$LAMBDA complete."
fi

    #################
    # PRODUCTION MD #
    #################
    echo "Starting production MD simulation..."

    cd ../
    mkdir Production_MD
    cd Production_MD
if ! grep 'Finished mdrun' md$LAMBDA.log
then
    $GMX/gmx grompp -f $MDP/Production_MD/md_$LAMBDA.mdp -c ../NPT/npt$LAMBDA.gro -p $FREE_ENERGY/topol.top -t ../NPT/npt$LAMBDA.cpt -o md$LAMBDA.tpr -maxwarn 2
    $GMX/gmx mdrun -v -ntmpi 1 -ntomp 12 -deffnm md$LAMBDA
    echo "Production MD complete."
else
    # End
    echo "Ending. Job completed for lambda = $LAMBDA"
fi

    cd $FREE_ENERGY
END

qsub -P em52 job"$i".job
else
echo Lambda $i job already run	
fi
done

if [ $(ls Lambda_*/Production_MD/md*.xvg | wc -l) -ge 21 ]
then
module load gromacs
gmx bar -f Lambda_*/Production_MD/md*.xvg -o -oi 
fi


exit
